# General settings
verbose: false
operations:
  - create-collection
  - ingest
#  - search  # Uncomment to run a search as part of the workflow

# Weaviate connection details (values can reference environment variables)
weaviate:
  url: "${WEAVIATE_URL}"
  api_key: "${WEAVIATE_API_KEY}"
  openai_api_key: "${OPENAI_APIKEY}"
  timeout: 30

# Collection configuration
collection:
  name: CourtCase
  vectorizer: text2vec-openai
  embedding_model: text-embedding-3-large
  force_recreate: false
  skip_create: false

# Ingestion settings
ingest:
  input: data/court_cases.json        # Path to your dataset (JSON/JSONL)
  input_format: auto                  # auto | json | jsonl
  data_key:                           # Set if the JSON root contains the array under a key
  id_field: id
  text_field: description
  title_field: title
  metadata_fields:
    - jurisdiction
    - filing_date
  limit:
  dry_run: true                       # Set to false to push data to Weaviate
  preview: 3
  log_every: 50

# Similarity search settings
search:
  collection: CourtCase
  query: motion to dismiss for lack of jurisdiction
  query_file:
  case_json:
  text_field: description
  title_field: title
  top_k: 5
  include_distance: true
  snippet_width: 180
  show_metadata: true
