name: hackathon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - nodejs=18
  - yarn
  - pip
  - requests
  - pip:
      - openai>=1.42.0
      - weaviate-client>=4.6.0,<5.0.0
      - pyyaml>=6.0.0
